server:
  port: 8083
dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://192.168.119.145
    port: 2181
    timeout: 100000
    parameters:
      blockUntilConnectedWait: 50
  protocol:
    name: dubbo