server:
  port: 8083
dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://192.168.119.147:2182
    timeout: 100000
    parameters:
      blockUntilConnectedWait: 250
  protocol:
    name: dubbo