server:
  port: 8081
dubbo:
  application:
    name: provide
  protocol:
    name: dubbo
    port: 28081
  registry:
    address: zookeeper://192.168.119.147:2182
    timeout: 100000
    parameters:
      blockUntilConnectedWait: 250